apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogapp-frontend
  template:
    metadata:
      labels:
        app: blogapp-frontend
    spec:
      containers:
        - name: blogapp-frontend
          image: punitj123/blogapp-frontend
          ports:
            - containerPort: 3000
