apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-app-frontend
  template:
    metadata:
      labels:
        app: blog-app-frontend
    spec:
      containers:
        - name: blog-app-frontend
          image: punitj123/blog-app-frontend
          ports:
            - containerPort: 3000
