apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogapp-backend
  template:
    metadata:
      labels:
        app: blogapp-backend
    spec:
      containers:
        - name: blog-app
          image: punitj123/blogapp-backend
          ports:
            - containerPort: 4500
